version: '3'
services:
  app:
    build: .
    environment:
      - DONT_PROMPT_WSL_INSTALL=1
    volumes:
      - type: bind
        source: .
        target: /workspaces
    ports:
      - "127.0.0.1:8000:8000"

